// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpf_ZpNpjBgoIYtTlhaN4Ah8aoBLs7Qto',
    appId: '1:108738144098:web:5e71357bf28d9e395b2e3b',
    messagingSenderId: '108738144098',
    projectId: 'vidconnect-73c0d',
    authDomain: 'vidconnect-73c0d.firebaseapp.com',
    storageBucket: 'vidconnect-73c0d.firebasestorage.app',
    measurementId: 'G-5JXG6H9N28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC74MF0O-GI_ROVOzXYDIjHUfAM80E1q7U',
    appId: '1:108738144098:android:c609267ea820404a5b2e3b',
    messagingSenderId: '108738144098',
    projectId: 'vidconnect-73c0d',
    storageBucket: 'vidconnect-73c0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwlVUh4VEqSjtoZmOGzo_TnzfaYa0D6Jc',
    appId: '1:108738144098:ios:d46b7c1f297684735b2e3b',
    messagingSenderId: '108738144098',
    projectId: 'vidconnect-73c0d',
    storageBucket: 'vidconnect-73c0d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
